<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SEO Audit Report - {{ $data['website_url'] }}</title>
    <style>
        @page {
            margin: 0;
        }
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            color: #2f3344;
            margin: 0;
            padding: 0;
            line-height: 1.5;
        }
        .header {
            background: #673ab7;
            color: white;
            padding: 40px;
            text-align: center;
        }
        .header h1 {
            margin: 0;
            font-size: 28px;
            letter-spacing: 1px;
        }
        .header p {
            margin: 10px 0 0;
            opacity: 0.8;
            font-size: 14px;
        }
        .container {
            padding: 40px;
        }
        .url-box {
            background: #f8f9fa;
            border: 1px solid #e3e4e8;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 30px;
            font-size: 14px;
        }
        .score-grid {
            overflow: hidden;
            margin-bottom: 40px;
        }
        .score-card {
            float: left;
            width: 22%;
            margin-right: 3%;
            background: white;
            border: 1px solid #e3e4e8;
            border-radius: 12px;
            padding: 20px;
            text-align: center;
        }
        .score-card:last-child {
            margin-right: 0;
        }
        .score-value {
            font-size: 24px;
            font-bold: bold;
            color: #673ab7;
            margin-bottom: 5px;
        }
        .score-label {
            font-size: 11px;
            text-transform: uppercase;
            color: #727586;
            letter-spacing: 1px;
        }
        .summary-box {
            margin-bottom: 40px;
        }
        .summary-box h2 {
            font-size: 18px;
            border-left: 4px solid #673ab7;
            padding-left: 12px;
            margin-bottom: 15px;
        }
        .summary-content {
            font-size: 15px;
            color: #515466;
            background: #fbfbfc;
            padding: 20px;
            border-radius: 10px;
        }
        .recommendations h2 {
            font-size: 18px;
            margin-bottom: 20px;
        }
        .rec-item {
            border: 1px solid #e3e4e8;
            border-radius: 10px;
            padding: 15px;
            margin-bottom: 15px;
            overflow: hidden;
        }
        .rec-type {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 4px;
            color: white;
            font-size: 10px;
            text-transform: uppercase;
            font-weight: bold;
            margin-bottom: 8px;
        }
        .type-critical { background: #ef4444; }
        .type-warning { background: #f59e0b; }
        .type-info { background: #3b82f6; }
        
        .rec-msg {
            font-size: 14px;
            color: #2f3344;
            font-weight: bold;
        }
        .footer {
            position: absolute;
            bottom: 40px;
            width: 100%;
            text-align: center;
            font-size: 12px;
            color: #a0aec0;
            border-top: 1px solid #f1f2f4;
            padding-top: 20px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>SEO AUDIT REPORT</h1>
        <p>Generated by SCASTOR AI Auditor • {{ date('M d, Y') }}</p>
    </div>

    <div class="container">
        <div class="url-box">
            <strong>Analyzed URL:</strong> {{ $data['website_url'] ?? 'N/A' }}
        </div>

        @if(isset($data['screenshots']) && count($data['screenshots']) > 0)
        <div style="margin-bottom: 30px;">
            <h2 style="font-size: 18px; border-left: 4px solid #673ab7; padding-left: 12px; margin-bottom: 20px;">Website Previews</h2>
            <div style="overflow: hidden;">
                @foreach($data['screenshots'] as $index => $imgUrl)
                <div style="float: left; width: 48%; margin-right: {{ $index % 2 == 0 ? '4%' : '0' }}; margin-bottom: 20px;">
                    <a href="{{ $data['website_url'] }}" target="_blank" style="text-decoration: none;">
                        <img src="{{ $imgUrl }}" style="width: 100%; border: 1px solid #e3e4e8; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.05);">
                        <div style="font-size: 10px; color: #727586; text-align: center; margin-top: 5px;">
                            {{ str_contains($imgUrl, 'mobile') ? 'Mobile View' : 'Desktop View' }} (Click to Preview)
                        </div>
                    </a>
                </div>
                @endforeach
            </div>
        </div>
        @endif

        <div class="score-grid">
            <div class="score-card">
                <div class="score-value">{{ $data['overall_score'] ?? 0 }}%</div>
                <div class="score-label">Overall</div>
            </div>
            <div class="score-card">
                <div class="score-value">{{ $data['performance_score'] ?? 0 }}%</div>
                <div class="score-label">Performance</div>
            </div>
            <div class="score-card">
                <div class="score-value">{{ $data['technical_seo_score'] ?? $data['technical_score'] ?? 0 }}%</div>
                <div class="score-label">Technical</div>
            </div>
            <div class="score-card">
                <div class="score-value">{{ $data['content_score'] ?? 0 }}%</div>
                <div class="score-label">Content</div>
            </div>
        </div>
        
        @if(isset($data['pagespeed']))
        <div class="summary-box">
            <h2>PageSpeed Insights ({{ $data['pagespeed']['scores']['performance'] ?? 0 }}%)</h2>
            <div class="score-grid" style="margin-top: 15px;">
                <div class="score-card" style="width: 21%; padding: 10px;">
                    <div class="score-value" style="font-size: 16px;">{{ $data['pagespeed']['metrics']['first_contentful_paint'] ?? 'N/A' }}</div>
                    <div class="score-label" style="font-size: 9px;">FCP</div>
                </div>
                <div class="score-card" style="width: 21%; padding: 10px;">
                    <div class="score-value" style="font-size: 16px;">{{ $data['pagespeed']['metrics']['largest_contentful_paint'] ?? 'N/A' }}</div>
                    <div class="score-label" style="font-size: 9px;">LCP</div>
                </div>
                <div class="score-card" style="width: 21%; padding: 10px;">
                    <div class="score-value" style="font-size: 16px;">{{ $data['pagespeed']['metrics']['total_blocking_time'] ?? 'N/A' }}</div>
                    <div class="score-label" style="font-size: 9px;">TBT</div>
                </div>
                <div class="score-card" style="width: 21%; padding: 10px;">
                    <div class="score-value" style="font-size: 16px;">{{ $data['pagespeed']['metrics']['cumulative_layout_shift'] ?? 'N/A' }}</div>
                    <div class="score-label" style="font-size: 9px;">CLS</div>
                </div>
            </div>
            <div style="font-size: 12px; color: #727586; margin-top: -20px;">
                <strong>Performance Strategy:</strong> Mobile | <strong>Experience:</strong> {{ $data['pagespeed']['loading_experience'] ?? 'UNKNOWN' }}
            </div>
        </div>
        @endif

        <div class="summary-box">
            <h2>Executive Summary</h2>
            <div class="summary-content">
                {{ $data['summary'] ?? 'No summary available.' }}
            </div>
        </div>

        <div class="summary-box">
            <h2>Website Section Audit</h2>
            <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
                @foreach($data['section_analysis'] ?? [] as $section)
                <tr style="border-bottom: 1px solid #f1f2f4;">
                    <td style="padding: 12px 0; width: 30%; font-weight: bold; color: #673ab7;">{{ $section['section'] ?? 'N/A' }}</td>
                    <td style="padding: 12px 0; width: 20%;">
                        <span style="padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; 
                            background: {{ ($section['status'] ?? '') == 'Good' ? '#10b981' : (($section['status'] ?? '') == 'Critical' ? '#ef4444' : '#f59e0b') }}; color: white;">
                            {{ $section['status'] ?? 'N/A' }}
                        </span>
                    </td>
                    <td style="padding: 12px 0; color: #515466;">{{ $section['analysis'] ?? '' }}</td>
                </tr>
                @endforeach
            </table>
        </div>

        <div class="recommendations">
            <h2>Expert Recommendations</h2>
            @foreach($data['recommendations'] ?? [] as $rec)
                <div class="rec-item">
                    <span class="rec-type type-{{ $rec['type'] ?? 'info' }}">{{ $rec['type'] ?? 'info' }}</span>
                    <div class="rec-msg">{{ $rec['message'] ?? '' }}</div>
                </div>
            @endforeach
        </div>
    </div>
    <div class="footer">
        &copy; {{ date('Y') }} SCASTOR AI. This is an AI-generated analysis based on available metadata.
    </div>
</body>
</html>
