name: Deploy project to our server
on:
  push:
    branches:
      - master
jobs:
  FTP-Deploy-Softvence:
    name: FTP-Deploy-Softvence
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies & Build assets
        run: |
          npm install
          npm run build

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER_NAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: public_html/ # আপনার সার্ভারের সঠিক পাথ দিন (যেমন: public_html/ অথবা /)
          protocol: ftp
          state-name: .ftp-deploy-sync-state.json
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            storage/*.key
            .env
            phpunit.xml
            README.md

          
